CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3360=y
CONFIG_PMW3360_CPI=1200
CONFIG_PMW3360_CPI_DIVIDOR=4
CONFIG_PMW3610_ORIENTATION_180=y
CONFIG_PMW3360_AUTOMOUSE_TIMEOUT_MS=500
CONFIG_PMW3360_MOVEMENT_THRESHOLD=0

CONFIG_ZMK_STUDIO_LOCKING=n